INSERT INTO streamer (first_name, last_name, matricule, email, age, chaine, rule, id) VALUES
('John', 'Doe', 'JD123', 'john.doe@example.com', 25, 'JohnDoeGaming', 2, 1),
('Jane', 'Smith', 'JS456', 'jane.smith@example.com', 30, 'JaneSmithPlays',  2, 2),
('Alice', 'Johnson', 'AJ789', 'alice.johnson@example.com', 28, 'AliceJ', 2, 3),
('Bob', 'Brown', 'BB101', 'bob.brown@example.com', 32, 'BobB', 2, 4),
('Charlie', 'Davis', 'CD102', 'charlie.davis@example.com', 22, 'CharlieD', 2, 5),
('David', 'Wilson', 'DW103', 'david.wilson@example.com', 27, 'DavidW', 2, 6),
('Eva', 'Martinez', 'EM104', 'eva.martinez@example.com', 29, 'EvaM', 2, 7),
('Frank', 'Miller', 'FM105', 'frank.miller@example.com', 35, 'FrankM', 2, 8),
('Grace', 'Lee', 'GL106', 'grace.lee@example.com', 24, 'GraceL', 2, 9),
('Hank', 'Taylor', 'HT1010', 'hank.taylor@example.com', 26, 'HankT', 2, 10),
('David', 'Hedgar', 'HT107', 'davidhedgar@yahoo.fr', 46, 'Z-Event', 3, 11);

INSERT INTO live (id, label, theme, date_start, date_end, pegi, streamer_id) VALUES
 (1, 'Live 1 by John', 'Gaming', NOW(), NOW(), 18, 1),
 (2, 'Live 2 by John', 'Discussion', NOW(), NOW(), 18, 1),
 (3, 'Live 1 by Jane', 'Cooking', NOW(), NOW(), 12, 2),
 (4, 'Live 2 by Jane', 'Travel', NOW(), NOW(), 12, 2),
 (5, 'Live 1 by Alice', 'Fitness', NOW(), NOW(), 16, 3),
 (6, 'Live 2 by Alice', 'Health', NOW(), NOW(), 16, 3),
 (7, 'Live 1 by Bob', 'Music', NOW(), NOW(), 15, 4),
 (8, 'Live 2 by Bob', 'Tech', NOW(), NOW(), 15, 4),
 (9, 'Live 1 by Charlie', 'Art', NOW(), NOW(), 10, 5),
 (10, 'Live 2 by Charlie', 'Education', NOW(), NOW(), 10, 5),
 (11, 'Live 1 by David', 'Science', NOW(), NOW(), 18, 6),
 (12, 'Live 2 by David', 'Nature', NOW(), NOW(), 18, 6),
 (13, 'Live 1 by Eva', 'Travel', NOW(), NOW(), 13, 7),
 (14, 'Live 2 by Eva', 'Lifestyle', NOW(), NOW(), 13, 7),
 (15, 'Live 1 by Frank', 'Sports', NOW(), NOW(), 16, 8),
 (16, 'Live 2 by Frank', 'Gaming', NOW(), NOW(), 16, 8),
 (17, 'Live 1 by Grace', 'Beauty', NOW(), NOW(), 14, 9),
 (18, 'Live 2 by Grace', 'Wellness', NOW(), NOW(), 14, 9),
 (19, 'Live 1 by Hank', 'Gaming', NOW(), NOW(), 18, 10),
 (20, 'Live 2 by Hank', 'Adventure', NOW(), NOW(), 18, 10);
